### ISSUE TITLE
Contrast issues in the title bar

### ISSUE THREAD

**Issue by JosephTLyons** [e-simpson/new-darcula-z#1]
Awesome theme - bringing me back to days when I was in JetBrains tooling.  There are some buttons where the icons / text aren't visible.

<img width="1438" alt="SCR-20240224-cfql" src="https://github.com/e-simpson/new-darcula-z/assets/19867440/e2950fcd-cbc7-44bd-b637-36de79703588">

**Comment by e-simpson** [comment]
@JosephTLyons thanks! There’s something about the JetBrains Darcula I just can’t give up. Will fix shortly!

**Comment by e-simpson** [comment]
@JosephTLyons submitted the PR. Should be updated shortly. If you notice any other contrast or visual issues please don't hesitate to open another issue - I haven't yet sorted out a good procedure to test out all of the theme-able attributes.

**Comment by e-simpson** [comment]
<img width="1292" alt="Screenshot 2024-02-24 at 9 10 09 AM" src="https://github.com/e-simpson/new-darcula-z/assets/25159851/e53cc7c0-538b-4e37-a6e7-d8071e98cd4c">

**Comment by JosephTLyons** [comment]
Awesome! Looking good on my end! Yeah, there is a bit of friction with making themes and plugins right now - hopefully we will smooth the edges of this process over time.
