### ISSUE TITLE
Contrast of excerpt headers in project search

### ISSUE THREAD

**Issue by JosephTLyons** [e-simpson/new-darcula-z#2]
<img width="1608" alt="SCR-20240225-brjg" src="https://github.com/e-simpson/new-darcula-z/assets/19867440/dae4d39a-fca8-4f90-9f33-70cbef62ebbf">

**Comment by e-simpson** [comment]
Thanks @JosephTLyons! This issue slipped past me. Will take care of this shortly.

**Comment by e-simpson** [comment]
Hi @JosephTLyons, sorry this issue notification must have slipped past me! Fixed this and some other things in 9fa13b1726d8ee9c7fffbc598d76a49b17a1c460. Thanks for testing and filing this issue!

<img width="1205" alt="Screenshot 2024-03-07 at 5 51 38 PM" src="https://github.com/e-simpson/new-darcula-z/assets/25159851/8fa84ee8-cf9a-48fa-9f48-a7d823268b32">
