### ISSUE TITLE
Background of popup is white

### ISSUE THREAD

**Issue by ProjectInfinity** [e-simpson/new-darcula-z#3]
Hi, as you can see in the provided the background of the diagnostic popup seem to be quite unreadable.

![image](https://github.com/e-simpson/new-darcula-z/assets/593870/dd1d3c7b-c069-4344-a618-1d4fc964962f)

I'm not sure if it matters, but I am using the Linux port of Zed.

**Comment by e-simpson** [comment]
Hi @ProjectInfinity, thanks for letting me know about this! 
Do you have a code snippet I can use to get to this popup? I can't seem to get it to show.

Update: nevermind, got it! Building update now...

**Comment by ProjectInfinity** [comment]
Awesome. When will it be available?

**Comment by e-simpson** [comment]
The Zed team usually merges within a few hours, should be out around 8PM EST or so 👍

**Comment by ProjectInfinity** [comment]
Hello again. I noticed it was available as an upgrade. Perhaps the Linux port is too early into development to upgrade the plugins but I uninstalled and reinstalled it and now the version sits at 1.0.4, however the issue still seems to occur as you can see in the uploaded image.

![image](https://github.com/e-simpson/new-darcula-z/assets/593870/ae194a0d-00ed-4d31-bfb7-80b5257675dc)
![image](https://github.com/e-simpson/new-darcula-z/assets/593870/9283780d-98e2-48c0-858c-02f7cbe378b8)

Update:
To add to this, I took the JSON contents and replaced the built in One theme with this and recompiled. Even doing this, it still is white. :(

**Comment by e-simpson** [comment]
@ProjectInfinity thanks for coming back with this, that screenshot really helped me centre down on this theme attribute!! Fixed it locally today, will push it tomorrow morning. Thanks for the persistence 😁

**Comment by e-simpson** [comment]
@ProjectInfinity update should merge in tomorrow morning.
