### ISSUE TITLE
Far too little contrast

### ISSUE THREAD

**Issue by YarekTyshchenko** [e-simpson/new-darcula-z#4]
Idk if its my monitor (or my eyes) but the contrast on this is far too low

**Comment by e-simpson** [comment]
Hi @YarekTyshchenko, ya this could be something with your monitor colour profile. Are there specific parts of the UI you find not enough contrast? The colours are similar to the original JetBrains theme which is intended to be less contrasty and easier on some eyes. 

I will say I could slightly increase the contrast of the muted text (file tree, etc.). And will try to add additional variants (high-contrast, light mode) for accessibility when I have the time.
