### ISSUE TITLE
Improve text legibility while using the embedded zed terminal

### ISSUE THREAD

**Issue by edgarkanyes** [e-simpson/new-darcula-z#7]
Autocomplete prompts are not readily visible when using the zed terminal. I've included screenshots below to show what I mean.

| One Dark Theme    | New Darcula Theme  |
|--------------------|-----------------|
| <img width="651" alt="Screenshot 2024-07-24 at 11 59 13" src="https://github.com/user-attachments/assets/9adb6610-860f-46ab-a95d-98745aa44e76"> | <img width="764" alt="Screenshot 2024-07-24 at 11 58 42" src="https://github.com/user-attachments/assets/e0722fae-581f-4678-90b7-1d4115b21f61"> |

**Comment by e-simpson** [comment]
@edgarkanyes thanks for the issue! Looking into this now..

**Comment by e-simpson** [comment]
Seems to be the `"terminal.ansi.bright_black"` key .. fixing now..

**Comment by e-simpson** [comment]
@edgarkanyes 1.0.6 update should go out within next day. Thanks again.

Update status: https://github.com/zed-industries/extensions/pull/1128
