### ISSUE TITLE
White text on white background in some places

### ISSUE THREAD

**Issue by sluramod** [e-simpson/new-darcula-z#9]
Hello,

First of all, thank you! I'm using version v1.0.6.

I noticed that in the following places I see white font on white background:

imports:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/519c9430-7565-4792-90f0-449997ea2386" />

type definitions:
<img width="263" alt="image" src="https://github.com/user-attachments/assets/b471b43b-00cc-46a4-8551-a7d0fec7c355" />

Otherwise, everything looks amazing to me. 

Thanks,
Alex

**Comment by e-simpson** [comment]
Hey @sluramod, thanks for this! Really appreciate you finding it. I have gone ahead and fixed this.. it seemed to be the `editor.document_highlight.write_background` theme variable.

[Submitted the update](https://github.com/zed-industries/extensions/pull/1834) for version 1.0.7, should be out by tomorrow. 

Best,
Evan
